"""
Utilities for performing a convergence analyis of the 1D elliptic PINN solver.

This module provides:
 - `run_1d_PINN_error_convergence` (function): call to run a convergence analysis using specified networks and collocation point numbers
 - `plot_PINN_convergence_results` (function): used to plot results of above.
"""

import os
# To support reproducibility
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

import numpy as np
import pandas as pd
import math
import tensorflow as tf   # See project README
import deepxde as dde
import itertools
from PINN_1d_elliptic import solve_1d_elliptic_PINN
import matplotlib.pyplot as plt




def plot_PINN_convergence_results(df):
    """
    Plots convergence results. Plots the final train loss, final test loss, l2 error, l_infty error, against number of 
    collocations points, for each network used. 

    Parameters:
        df : dataframe
            Summary dataframe generated by PINN_error_convergence
    """
    # uncomment for publication version of figure
    #plt.rcParams.update({'font.size': 14,
    #                     'axes.labelsize': 14,
    #                     'xtick.labelsize': 14,
    #                     'ytick.labelsize': 14,
    #                     'legend.fontsize': 14,
    #                     'lines.linewidth': 1.8,
    #                     'lines.markersize': 6})
    
    
    fig, ax = plt.subplots(2,2,constrained_layout=True)

    num_trainable_parameters_list = np.unique(
        df["num_trainable_params"].values
    )

    markers = ['o', 's', '^', 'D', 'v', 'P', 'X']
    
    for i, ntp in enumerate(num_trainable_parameters_list):
        df_restricted = df[df['num_trainable_params']==ntp]
        fmt = markers[i % len(markers)] + '-'
        
        nl = df_restricted['num_layers'].iloc[0]
        npl = df_restricted['neurons_per_layer'].iloc[0]
        arch_str = f"{nl} x {npl} network"
        
        ax[0,0].loglog(df_restricted['num_colloc'], df_restricted['loss_train_median'], fmt, label = arch_str)
        ax[0,0].fill_between(df_restricted['num_colloc'], df_restricted['loss_train_min'], df_restricted['loss_train_max'], alpha=0.2)

        ax[0,1].loglog(df_restricted['num_colloc'], df_restricted['loss_test_median'],  fmt)
        ax[0,1].fill_between(df_restricted['num_colloc'], df_restricted['loss_test_min'], df_restricted['loss_test_max'], alpha=0.2)

        ax[1,0].loglog(df_restricted['num_colloc'], df_restricted['err_l2_median'],     fmt)
        ax[1,0].fill_between(df_restricted['num_colloc'], df_restricted['err_l2_min'], df_restricted['err_l2_max'], alpha=0.2)

        ax[1,1].loglog(df_restricted['num_colloc'], df_restricted['err_inf_median'],    fmt)
        ax[1,1].fill_between(df_restricted['num_colloc'], df_restricted['err_inf_min'], df_restricted['err_inf_max'], alpha=0.2)

    ax[1,0].set_xlabel('Num collocation points')
    ax[1,1].set_xlabel('Num collocation points')
    ax[0,0].set_ylabel('Train loss')
    ax[0,1].set_ylabel('Test loss')
    ax[1,0].set_ylabel('$l_2$ error')
    ax[1,1].set_ylabel('$l_{\infty}$ error') 
    
    handles, labels = ax[0,0].get_legend_handles_labels()
    fig.legend(handles, labels, bbox_to_anchor=(0.5, 1.), loc='lower center')
            
    #fig.set_size_inches(7.1, 5.5)    
    #fig.savefig('Figure2.pdf', bbox_inches='tight')       # vector
    #fig.savefig('Figure2.eps', bbox_inches='tight')       # vector
    #fig.savefig('Figure2.png', dpi=300, bbox_inches='tight')  # raster backup
    #fig.savefig('Figure2.png', dpi=300, bbox_inches='tight')  # raster backup


    
  
def run_1d_PINN_error_convergence(mms_problem,
                                  seeds,
                                  architectures,
                                  num_colloc_array, 
                                  num_epochs,
                                  train_distribution,
                                  use_best_test_loss,
                                  learning_rate_decay,
                                  output_file = None):
    """
    Using the solve_1d_elliptic_PINN() function, perform an error convergence analysis varying the number of
    collocation points or the network architecture
    
    
    Parameters:
        mms_problem : string
           Should be "MMS1" or "MMS2". For MMS1, f(x) = -4*pi*pi*tf.math.sin(2*pi*x), g = 2*pi (solution is sinusoidal),
           for "MMS2" f(x) = (4*(x-0.5)**2 - 2)*tf.math.exp(-(x-0.5)**2) and g = -np.exp(-0.25) (solution is exponential)
        architectures : array of 2d-arrays
            array of architectures to use, e.g., [[2,10],[4,10],[4,20]]. Each entry should be [num_layers,neurons_per_layer]
        num_colloc_array : array
            array of integers, number of collocation points to be used
        num_epochs : int
            Number of epochs (iterations). Passed into PINN_Solve. 
        train_distribution : string
            How the collocation points will be distributed. Will be passed to dde.data.PDE(). Options
            include "uniform" or "pseudo" (randomly re-sampled each epoch). Passed into PINN_Solve. 
        use_best_test_loss : boolean
            Saves and restores the best performing weights, i.e., the weights for the iteration that provided 
            the lowest test loss. Passed into PINN_Solve. 
        output_file : string
            CSV file to be created containing all combinations of the results. All combinations of num_colloc, num_layers, 
            and num_neurons_per_layer will be run
    Returns:
        dataframe of results (also saved to output_file)
        Also creates and saves a summary dataframe to the file "{output_file_stem}_SUMMARY.csv" - contains means, std, min and max across all runs
    """         
    
    
    # Helper function - computes the total number of trainable parameters in a network
    # given the number of layers and the number of neurons in each layer, 
    def get_num_trainable_params(num_layers, neurons_per_layer):
        return (num_layers+2)*neurons_per_layer + neurons_per_layer*neurons_per_layer*(num_layers-1) + 1 

    results = []

    assert(len(seeds)>0)

    total = len(architectures) * len(num_colloc_array) * len(seeds)

    # loop over all combinations of specificed inputs
    for i, (arch, nc, seed) in enumerate(itertools.product(architectures, num_colloc_array, seeds)):
        
        nl = arch[0] 
        assert(nl>0)
        npl = arch[1]
        assert(npl>0)
            
        print("==========================================")
        print(f"Run {i+1}/{total}: nc={nc}, nl={nl}, npl={npl} [seed={seed}]")
        print("==========================================")
        
        tf.keras.backend.clear_session()   # Useful to include in new solves to avoid gradual slow-down
        tf.compat.v1.reset_default_graph() # Useful to include in new solves to avoid gradual slow-down
        
        pi = tf.constant(math.pi)

        # Set up the problem to be solved
        if mms_problem == "MMS1":    
            bc = 2*pi
            def f(x):
                return - 4*pi*pi*tf.math.sin(2*pi*x)
            def exact_soln(x):
                return np.sin(2*np.pi*x)          
        elif mms_problem == "MMS2":
            bc = -np.exp(-0.25)
            def f(x):
                return (4*(x-0.5)**2 - 2)*tf.math.exp(-(x-0.5)**2)
            def bc_func(x):
                return 
            def exact_soln(x):
                return np.exp(-(x-0.5)**2) - np.exp(-0.25)   
        else:
            raise ValueError("mms_problem should be 'MMS1' or 'MMS2'")


        N = 1001 # number of output points for the solve
        x, u, soln_info = solve_1d_elliptic_PINN(f, 
                                                 bc,                
                                                 num_output_points = N,
                                                 num_colloc = nc,
                                                 num_layers = nl,
                                                 neurons_per_layer = npl,
                                                 num_epochs = num_epochs,
                                                 train_distribution=train_distribution,
                                                 use_best_test_loss = use_best_test_loss,
                                                 learning_rate_decay = learning_rate_decay,
                                                 seed = seed)
        u_true = exact_soln(x)
        
        """
        from matplotlib import pyplot as plt
        fig, ax = plt.subplots()
        ax.plot(x,u,'r')
        ax.plot(x,u_true,'k')
        ax.set_title(f"NC = {nc}, NL = {nl}, NPL = {npl}")
        fig, ax = plt.subplots()
        ax.plot(soln_info['colloc_points'],soln_info['resid_at_colloc'],'k*')
        ax.plot(soln_info['x_dense'],soln_info['resid_at_x_dense'],'b')
        ax.set_title(f"NC = {nc}, NL = {nl}, NPL = {npl}")
        """

        err_l2  = np.linalg.norm(u-u_true)/np.sqrt(N)
        err_inf = np.max(np.abs(u-u_true))

        num_trainable_params = get_num_trainable_params(nl, npl)

        # final loss on training and test points (PDE component only)
        loss_train = soln_info['loss_train']
        loss_test = soln_info['loss_test']        
        
        results.append(
            {"seed":seed,
             "num_colloc": nc,
             "num_layers": nl,
             "neurons_per_layer": npl,
             "num_trainable_params": num_trainable_params, 
             "err_l2": err_l2,
             "err_inf": err_inf,
             "loss_train": loss_train,
             "loss_test": loss_test})

        # save the current results rather than wait until the end, in case run is interrupted.
        df = pd.DataFrame(results)
        if output_file is not None:
            df.to_csv(output_file, index=False)    # save without the auto-generated index
        

    output_cols = df.columns[-4:]
    group_cols = [c for c in df.columns if c not in ['seed', *output_cols]]

    df_summary = df.groupby(group_cols, as_index=False).agg(
        {
            col: ['median', 'mean', 'min', 'max'] 
            for col in output_cols
        })

    df_summary.columns = [ '_'.join(x).rstrip('_') if isinstance(x, tuple) else x for x in df_summary.columns]        


    if output_file is not None:
        df.to_csv(output_file, index=False)    # save without the auto-generated index
        summary_output_file = output_file[:-4] + "_SUMMARY.csv" if output_file.endswith('.csv') else output_file + "_SUMMARY.csv"
        df_summary.to_csv(summary_output_file, index=False) 
        
    return df


